title: Suleman Shahnawaz Manji
description: Technical Problem-Solver | IT Professional specializing in AI, Automation, and Optimization
author: Suleman Shahnawaz Manji
email: 89.suleman.manji@gmail.com
url: "https://www.sulemanji.com"
baseurl: ""

# Remote theme configuration
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-sitemap
- jekyll-seo-tag

# Professional information
linkedin_url: "https://www.linkedin.com/in/suleman-manji-1a46852a0"
github_username: ssmanji89
location: "IT Professional"
tagline: "Capable Problem-Solver specializing in AI, Automation, and Optimization"

# Site settings
show_downloads: false
google_analytics: 
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Professional focus areas
focus_areas:
  - "Artificial Intelligence & Machine Learning"
  - "Process Automation & Optimization"
  - "Systems Integration & Analytics"

# Assessment-driven capabilities
core_strengths:
  - "Analytical Problem-Solving"
  - "Hands-On Technical Implementation"
  - "Collaborative Team Contribution"
  - "Structured System Optimization"

exclude:
  - .venv/
  - personal-assessment-profile.md 