title: Suleman Manji
email: ssmanji89@gmail.com
description: Enterprise Technology Strategy | Cloud Architecture | Process Automation

# Theme configuration
remote_theme: pages-themes/modernist@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed

# Theme-specific configurations
show_downloads: false
google_analytics: 

# Site settings
domain: www.sulemanji.com
url: https://www.sulemanji.com
baseurl: ""

# Social profiles
github_username: ssmanji89
linkedin_username: suleman-manji-1a46852a0

# Build settings
markdown: kramdown
sass:
  style: compressed

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name

# Default front matter
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
