title: Suleman Manji
email: ssmanji89@gmail.com
description: Enterprise Technology Transformation | Business Process Automation | Strategic Innovation

remote_theme: pages-themes/hacker@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

domain: www.sulemanji.com
url: https://www.sulemanji.com

navigation:
  - title: Home
    url: /
  - title: Experience
    url: /experience
  - title: Transformation Projects
    url: /transformation-projects
  - title: Business Process Automation
    url: /bpa
  - title: Projects
    url: /projects
  - title: Philosophy
    url: /philosophy

github_username: ssmanji89
linkedin_username: suleman-manji-1a46852a0

# Build settings
markdown: kramdown

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
